### ISSUE TITLE
Clicking title doesn't work

### ISSUE THREAD

**Issue by apple77y** [nhn/toast-ui.doc#1]
**Describe the bug**
Like the below image that I attach, that title doesn't let me move to the position.

**To Reproduce**
1. Click the title that I emphasize

**Expected behavior**

**Screenshots**
![screeshot](https://user-images.githubusercontent.com/11900262/70582545-2daa4c80-1bfe-11ea-8f17-d2dddf32b027.png)

**Comment by apple77y** [comment]
I can see that @seonim-ryu is the only one maintaining this project.
Please check this anytime you are enable.

**Comment by seonim-ryu** [comment]
@apple77y 
Thanks for reporting the issue! I modified the link and updated the README file on GitHub.
And we welcome contributing, so if you have a chance next time you can give us a PR. 🙏
